

package Formula1;

import javax.swing.JOptionPane;

public class jfU extends javax.swing.JFrame implements Enum{

    /** Creates new form jfU */
    public jfU() {
        initComponents();
        this.setTitle ("USUARIOS");
        setDefaultCloseOperation(jfU.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bInscribirseEnCurso = new javax.swing.JRadioButton();
        bConsultarCurso = new javax.swing.JRadioButton();
        bBorrarseDeCurso = new javax.swing.JRadioButton();
        bConsultarVidaLaboral = new javax.swing.JRadioButton();
        bEditarAlumno = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        bInscribirseEnOferta = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Historial = new javax.swing.JTextArea();
        bLimpiarHistorial = new javax.swing.JButton();
        bRealizarAccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

        buttonGroup1.add(bInscribirseEnCurso);
        bInscribirseEnCurso.setText("Inscibirse en Curso");

        buttonGroup1.add(bConsultarCurso);
        bConsultarCurso.setText("Consultar Curso");
        bConsultarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarCursoActionPerformed(evt);
            }
        });

        buttonGroup1.add(bBorrarseDeCurso);
        bBorrarseDeCurso.setText("Borrarse de Curso");
        bBorrarseDeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarseDeCursoActionPerformed(evt);
            }
        });

        buttonGroup1.add(bConsultarVidaLaboral);
        bConsultarVidaLaboral.setText("Consultar Vida Laboral");
        bConsultarVidaLaboral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarVidaLaboralActionPerformed(evt);
            }
        });

        buttonGroup1.add(bEditarAlumno);
        bEditarAlumno.setText("Editar datos de Alumno");
        bEditarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bInscribirseEnCurso)
                    .addComponent(bConsultarCurso)
                    .addComponent(bBorrarseDeCurso)
                    .addComponent(bConsultarVidaLaboral)
                    .addComponent(bEditarAlumno))
                .addContainerGap(495, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(bInscribirseEnCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bConsultarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bBorrarseDeCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bConsultarVidaLaboral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bEditarAlumno)
                .addGap(4, 4, 4))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Demandante"));

        buttonGroup1.add(bInscribirseEnOferta);
        bInscribirseEnOferta.setText("Inscribirse en Oferta");
        bInscribirseEnOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInscribirseEnOfertaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bInscribirseEnOferta)
                .addContainerGap(507, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bInscribirseEnOferta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Historial.setColumns(20);
        Historial.setRows(5);
        jScrollPane1.setViewportView(Historial);

        bLimpiarHistorial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bLimpiarHistorial.setText("Limpiar Historial");
        bLimpiarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarHistorialActionPerformed(evt);
            }
        });

        bRealizarAccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bRealizarAccion.setText("Realizar Acción");
        bRealizarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizarAccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bRealizarAccion)
                        .addGap(18, 18, 18)
                        .addComponent(bLimpiarHistorial)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRealizarAccion)
                    .addComponent(bLimpiarHistorial))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bInscribirseEnOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInscribirseEnOfertaActionPerformed
        Historial.setText("");
}//GEN-LAST:event_bInscribirseEnOfertaActionPerformed

    private void bLimpiarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarHistorialActionPerformed
        Historial.setText("");
}//GEN-LAST:event_bLimpiarHistorialActionPerformed

    private void bConsultarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarCursoActionPerformed
        Historial.setText("");
    }//GEN-LAST:event_bConsultarCursoActionPerformed

    private void bBorrarseDeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarseDeCursoActionPerformed
        Historial.setText("");
    }//GEN-LAST:event_bBorrarseDeCursoActionPerformed

    private void bConsultarVidaLaboralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarVidaLaboralActionPerformed
        Historial.setText("");
    }//GEN-LAST:event_bConsultarVidaLaboralActionPerformed

    private void bEditarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarAlumnoActionPerformed
        Historial.setText("");
    }//GEN-LAST:event_bEditarAlumnoActionPerformed

    private void bRealizarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizarAccionActionPerformed
// Inscribir en Curso
        if (bInscribirseEnCurso.isSelected()) {
          if(!Formula1UI.inem.cursos.isEmpty()){
            pInscribirse Inscribirse = new pInscribirse();

            if(JOptionPane.showConfirmDialog(this, Inscribirse, "Inscribirse en Curso",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
            == JOptionPane.OK_OPTION) {

                long aux= Inscribirse.getDNI();
                int aux2= Inscribirse.getIdentificador();
                for (Usuario u: Formula1UI.inem.usuarios) {
                    if (u.DNI==aux){
                        Formula1UI.inem.cursos.get(aux2-1).añadirAlumno(u);
                        Historial.setText ("El usuario con DNI "+ aux+
                                " se ha inscrito en el curso "+ aux2);
                    }
                }
            }}else{
                Historial.setText("No hay Cursos Ofertados");
            }
//Borrarse de Curso
        }else if (bBorrarseDeCurso.isSelected()) {
          if(!Formula1UI.inem.cursos.isEmpty()){
            pBorrarse Borrarse = new pBorrarse();

            if(JOptionPane.showConfirmDialog(this,Borrarse, "Borrarse de Curso",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
            == JOptionPane.OK_OPTION) {

                long aux= Borrarse.getDNI();
                int aux2= Borrarse.getIdentificador();
                for (Usuario u: Formula1UI.inem.usuarios) {
                    if (u.DNI==aux){
                        Formula1UI.inem.cursos.get(aux2-1).borrarAlumno(u);
                        Historial.setText ("El usuario con DNI "+ aux
                                + " se ha borrado del curso "+ aux2);
                    }
                }
            }}else{
                Historial.setText("No hay Cursos Ofertados");
            }
// Consultar Curso
        }else if (bConsultarCurso.isSelected()) {
          if(!Formula1UI.inem.cursos.isEmpty()){
            pConsultar consultar = new pConsultar();

            if(JOptionPane.showConfirmDialog(this, consultar, "Usuarios",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
            == JOptionPane.OK_OPTION) {

                long aux= consultar.getDNI();
                for (Usuario u: Formula1UI.inem.usuarios) {
                    if (u.getDNI()==aux){
                        String s=Formula1UI.inem.cCurso(u);
                        Historial.setText(s);
                    }
                }
            }
           }else{
                Historial.setText("No hay Cursos Ofertados");
           }
// Vida Laboral
        }else if (bConsultarVidaLaboral.isSelected()) {
            pVidaLaboral laboral = new pVidaLaboral();

            if(JOptionPane.showConfirmDialog(this, laboral, "Vida Laboral",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
            == JOptionPane.OK_OPTION) {

                long aux= laboral.getDNI();
                for (Usuario u: Formula1UI.inem.usuarios) {
                    if (u.getDNI()==aux){
                        if(!u.lista.isEmpty()){
                            String x= Formula1UI.inem.consultarVidaLaboral(u);
                            Historial.setText (x);
                        }else{
                            Historial.setText ("No ha Trabajado Antes");
                        }
                    }
                }
        }
// Editar Alumno
        }else if (bEditarAlumno.isSelected()) {
            pEditarAlumno editar = new pEditarAlumno();

            if(JOptionPane.showConfirmDialog(this, editar, "Editar Alumno",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
            == JOptionPane.OK_OPTION) {

                long aux= editar.getDNI();
                for (Curso c: Formula1UI.inem.cursos) {
                    for (Usuario u1: c.alumnos) {
                        if (u1.getDNI()==aux) {
                            c.editarAlumno(u1, editar.getDireccion(),
                                    editar.getTelefono(), editar.getCP(),
                                    editar.getLocalidad());
                            Historial.setText ("Se ha modificado el Alumno con "
                                    + "DNI "+aux);
                        }
                    }//end for2
                }// end for1
            }//end panel
// Inscribirse en Oferta
        }else if (bInscribirseEnOferta.isSelected()) {
            pInsEnOferta oferta = new pInsEnOferta();

            if(JOptionPane.showConfirmDialog(this, oferta, "Inscribirse en Oferta",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
            == JOptionPane.OK_OPTION) {

                int cont=1;
                long aux= oferta.getDNI();
                int aux2= oferta.getIdentificador();
                for (Usuario u: Formula1UI.inem.usuarios) {
                    if (u.getDNI()==aux){
                        for(Empresa e:Formula1UI.inem.empresas){
                            for (OfertaDeEmpleo o: e.lisOfertas) {
                                if (cont==aux2){
                                    o.InsertarEnOferta(u);
                                    Formula1UI.inem.demandante.lisDemandantes.add(u);
                                    u.setEstado(E1.TRABAJANDO);
                                    Historial.setText ("El demandante con DNI "+ aux
                                    +" se ha inscrito en la oferta "+ aux2);
                                }
                               cont ++;
                            }// end for3
                        }//end for2
                    }
                }//end for 1
         }// end panel
        }
     if (Historial.getText().equals("")){
        Historial.setText ("No hay ningún Usuario con ese DNI");
     }
    }//GEN-LAST:event_bRealizarAccionActionPerformed
// END FUNCTION.
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Historial;
    private javax.swing.JRadioButton bBorrarseDeCurso;
    private javax.swing.JRadioButton bConsultarCurso;
    private javax.swing.JRadioButton bConsultarVidaLaboral;
    private javax.swing.JRadioButton bEditarAlumno;
    private javax.swing.JRadioButton bInscribirseEnCurso;
    private javax.swing.JRadioButton bInscribirseEnOferta;
    private javax.swing.JButton bLimpiarHistorial;
    private javax.swing.JButton bRealizarAccion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
