/*
 * 
 * 
 */
package Formula1;

public class jpAñadeCoche extends javax.swing.JPanel implements Enum {

    /** Creates new form pEditarAlumno */
    public jpAñadeCoche() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        lModelo = new javax.swing.JLabel();
        tModelo = new javax.swing.JTextField();
        lCaracteristicasTecnicas = new javax.swing.JLabel();
        lMotor = new javax.swing.JLabel();
        tMotor = new javax.swing.JTextField();
        lAerodinamica = new javax.swing.JLabel();
        tAerodinamica = new javax.swing.JTextField();
        lNeumaticos = new javax.swing.JLabel();
        tNeumaticos = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Añadir Coche"));

        lModelo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lModelo.setText("Modelo:");

        lCaracteristicasTecnicas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lCaracteristicasTecnicas.setText("Caracteristicas Tecnicas:");

        lMotor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lMotor.setText("Reflejos:");

        lAerodinamica.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lAerodinamica.setText("Aerodinamica:");

        lNeumaticos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lNeumaticos.setText("Neumaticos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lModelo)
                        .addGap(28, 28, 28)
                        .addComponent(tModelo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lCaracteristicasTecnicas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lAerodinamica)
                            .addComponent(lNeumaticos)
                            .addComponent(lMotor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tNeumaticos, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tAerodinamica, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lModelo)
                    .addComponent(tModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCaracteristicasTecnicas)
                    .addComponent(tMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMotor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tAerodinamica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAerodinamica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNeumaticos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNeumaticos))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getModelo(){
        String s= "Sin Modelo";
        if (!tModelo.getText().equals("")){
            return tModelo.getText();
        }else{
            return s;
        }
    }
     
    public CaracteristicasTecnicasCoche getCaracteristicasTecnicas () {
        float motor = 0;
        float aerodinamica = 0;
        float neumaticos = 0;
        
        if (!tMotor.getText().equals("")){
            motor = Float.parseFloat(tMotor.getText());
        }
        if (!tAerodinamica.getText().equals("")){
            aerodinamica = Float.parseFloat(tAerodinamica.getText());
        }
        if (!tNeumaticos.getText().equals("")){
            neumaticos = Float.parseFloat(tNeumaticos.getText());
        }
       
        return new CaracteristicasTecnicasCoche(motor,aerodinamica,neumaticos);               
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel lAerodinamica;
    private javax.swing.JLabel lCaracteristicasTecnicas;
    private javax.swing.JLabel lModelo;
    private javax.swing.JLabel lMotor;
    private javax.swing.JLabel lNeumaticos;
    private javax.swing.JTextField tAerodinamica;
    private javax.swing.JTextField tModelo;
    private javax.swing.JTextField tMotor;
    private javax.swing.JTextField tNeumaticos;
    // End of variables declaration//GEN-END:variables

}
