
package Formula1;

import javax.swing.JOptionPane;

public class jpE extends javax.swing.JFrame {

    /** Creates new form jpE */
    public jpE() {        
        initComponents();
        setDefaultCloseOperation(jpE.DISPOSE_ON_CLOSE);
        this.setTitle ("EMPRESAS");
        listaempresas.setText(Formula1UI.inem.mostrarEmpresas()
                +"El numero total de empresas es: " + Formula1UI.inem.empresas.size());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bAltaOferta = new javax.swing.JRadioButton();
        bBajaOferta = new javax.swing.JRadioButton();
        bConsultaOferta = new javax.swing.JRadioButton();
        bModificacionOferta = new javax.swing.JRadioButton();
        jAccionEmpresa = new javax.swing.JButton();
        bIden = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaempresas = new javax.swing.JTextArea();
        bAviso = new javax.swing.JLabel();
        blisempresas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresa"));

        buttonGroup1.add(bAltaOferta);
        bAltaOferta.setText("Alta Oferta");
        bAltaOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAltaOfertaActionPerformed(evt);
            }
        });

        buttonGroup1.add(bBajaOferta);
        bBajaOferta.setText("Baja Oferta");
        bBajaOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBajaOfertaActionPerformed(evt);
            }
        });

        buttonGroup1.add(bConsultaOferta);
        bConsultaOferta.setText("Consultar Oferta");
        bConsultaOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultaOfertaActionPerformed(evt);
            }
        });

        buttonGroup1.add(bModificacionOferta);
        bModificacionOferta.setText("Modificar Oferta");
        bModificacionOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificacionOfertaActionPerformed(evt);
            }
        });

        jAccionEmpresa.setText("RealizarAccion");
        jAccionEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccionEmpresaActionPerformed(evt);
            }
        });

        jLabel1.setText("Con identificador:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jAccionEmpresa)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bModificacionOferta)
                        .addContainerGap(211, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bConsultaOferta)
                        .addContainerGap(207, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bBajaOferta)
                        .addContainerGap(233, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bAltaOferta)
                        .addContainerGap(235, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bIden, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bIden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(bAltaOferta)
                        .addGap(18, 18, 18)
                        .addComponent(bBajaOferta)
                        .addGap(18, 18, 18)
                        .addComponent(bConsultaOferta)
                        .addGap(18, 18, 18)
                        .addComponent(bModificacionOferta))
                    .addComponent(jAccionEmpresa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        listaempresas.setColumns(20);
        listaempresas.setRows(5);
        jScrollPane1.setViewportView(listaempresas);

        bAviso.setBackground(new java.awt.Color(255, 0, 0));
        bAviso.setForeground(new java.awt.Color(255, 0, 0));

        blisempresas.setText("Mostrar Empresas");
        blisempresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blisempresasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(blisempresas)
                        .addGap(304, 304, 304))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(bAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blisempresas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAccionEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccionEmpresaActionPerformed
     
     if((!Formula1UI.inem.empresas.isEmpty()) && (!bIden.getText().equals(""))){ // Si existen Empresas
        int x= Integer.parseInt(bIden.getText())-1;
//Alta Oferta
        if (bAltaOferta.isSelected()) {
            jpEAlta pEalta = new jpEAlta();
            if(JOptionPane.showConfirmDialog(this, pEalta, "Oferta",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
            == JOptionPane.OK_OPTION) {                                
            Formula1UI.inem.empresas.get(x).altaOferta(pEalta.getDescripcion(),
            pEalta.getEstudios(),pEalta.getContrato(),pEalta.getSalario());
            bAviso.setText ("La Oferta se ha insertado satisfactoriamente");
              }
//Baja Oferta
        } else if (bBajaOferta.isSelected()){
          if(Formula1UI.inem.empresas.get(x).getNumOfertas() != 0){
            jpEBaja pEbaja = new jpEBaja(x);
            if(JOptionPane.showConfirmDialog(this, pEbaja, "Ofertas",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
            == JOptionPane.OK_OPTION) {               
            OfertaDeEmpleo oferta= Formula1UI.inem.empresas.get(x).lisOfertas.get(pEbaja.getNumero()-1);
            Formula1UI.inem.empresas.get(x).bajaOferta(oferta);
            bAviso.setText ("La Oferta se ha borrado satisfactoriamente");
            }
          }else{
               bAviso.setText("No tiene Ofertas");
          }
// Consultar Oferta
        } else if (bConsultaOferta.isSelected()){            
            if(Formula1UI.inem.empresas.get(x).getNumOfertas() != 0){
                jpEConsulta pEconsulta = new jpEConsulta();
             if(JOptionPane.showConfirmDialog(this, pEconsulta, "Ofertas",
             JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
             == JOptionPane.OK_OPTION) {                 
                int salario = pEconsulta.getSalario();
                StringBuilder s= new StringBuilder();
                for (OfertaDeEmpleo of: Formula1UI.inem.empresas.get(x).lisOfertas){
                    if (of.getRangoSalarial()== salario){
                       s.append(Formula1UI.inem.empresas.get(x).
                       consultaOferta(of).toString());
                    }
                }
                listaempresas.setText(s.toString());
                }
            }else{
               bAviso.setText("No tiene Ofertas");              
            }
//Modificar Oferta
        } else if (bModificacionOferta.isSelected()){
            if(Formula1UI.inem.empresas.get(x).getNumOfertas() != 0){
                jpEModifica pEmodif = new jpEModifica(x);
            if(JOptionPane.showConfirmDialog(this, pEmodif, "Empresa",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
            == JOptionPane.OK_OPTION) {
               Formula1UI.inem.empresas.get(x).modificacionOferta(
               pEmodif.getNumero(),pEmodif.getDescripcion(),
               pEmodif.getEstudios(),pEmodif.getContrato(),pEmodif.getSalario());
               bAviso.setText("Modificado con Exito");
            }
            }else{
               bAviso.setText("No tiene Ofertas");
            }
        }
     }else{                                        // Si no existen Empresas
        bAviso.setText("No hay Empresas o no ha introducido un número");
     }
}//GEN-LAST:event_jAccionEmpresaActionPerformed

    private void blisempresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blisempresasActionPerformed
        listaempresas.setText(Formula1UI.inem.mostrarEmpresas()
        +"El numero total de empresas es: " + Formula1UI.inem.empresas.size());
    }//GEN-LAST:event_blisempresasActionPerformed

    private void bAltaOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAltaOfertaActionPerformed
       bAviso.setText ("");
    }//GEN-LAST:event_bAltaOfertaActionPerformed

    private void bBajaOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBajaOfertaActionPerformed
        bAviso.setText ("");
    }//GEN-LAST:event_bBajaOfertaActionPerformed

    private void bConsultaOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultaOfertaActionPerformed
        bAviso.setText ("");
    }//GEN-LAST:event_bConsultaOfertaActionPerformed

    private void bModificacionOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificacionOfertaActionPerformed
        bAviso.setText ("");
    }//GEN-LAST:event_bModificacionOfertaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jpE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bAltaOferta;
    private javax.swing.JLabel bAviso;
    private javax.swing.JRadioButton bBajaOferta;
    private javax.swing.JRadioButton bConsultaOferta;
    private javax.swing.JTextField bIden;
    private javax.swing.JRadioButton bModificacionOferta;
    private javax.swing.JButton blisempresas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jAccionEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listaempresas;
    // End of variables declaration//GEN-END:variables

}
