package Formula1;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class jpEscuderia extends javax.swing.JFrame {

    
    public jpEscuderia() {
        initComponents();
        this.setTitle ("Dueño Escuderia");
        setDefaultCloseOperation(jpEscuderia.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agrupados = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bConsultarEscuderia = new javax.swing.JRadioButton();
        bConsultarEscuderia1 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        bAnyadirPiloto = new javax.swing.JRadioButton();
        bModificarPiloto = new javax.swing.JRadioButton();
        bBorrarPiloto = new javax.swing.JRadioButton();
        bConsultarPiloto = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        bAnyadirCircuito = new javax.swing.JRadioButton();
        bModificarCircuito = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultados = new javax.swing.JTextArea();
        Accion = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        bAnyadirCircuito1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dueño Escuderia"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Escuderia:"));
        jPanel2.setToolTipText("");

        Agrupados.add(bConsultarEscuderia);
        bConsultarEscuderia.setText("Informacion");
        bConsultarEscuderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarEscuderiaActionPerformed(evt);
            }
        });

        Agrupados.add(bConsultarEscuderia1);
        bConsultarEscuderia1.setText("Elegir coche y piloto para mundial");
        bConsultarEscuderia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarEscuderia1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bConsultarEscuderia)
                    .addComponent(bConsultarEscuderia1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bConsultarEscuderia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bConsultarEscuderia1)
                .addGap(26, 26, 26))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pilotos:"));

        Agrupados.add(bAnyadirPiloto);
        bAnyadirPiloto.setText("Descartar piloto");

        Agrupados.add(bModificarPiloto);
        bModificarPiloto.setText("Fichar piloto libre");

        Agrupados.add(bBorrarPiloto);
        bBorrarPiloto.setText("Fichar piloto de otra escuderia");

        Agrupados.add(bConsultarPiloto);
        bConsultarPiloto.setText("Intercambiar piloto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAnyadirPiloto)
                    .addComponent(bModificarPiloto)
                    .addComponent(bBorrarPiloto)
                    .addComponent(bConsultarPiloto)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(bAnyadirPiloto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bModificarPiloto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bBorrarPiloto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bConsultarPiloto))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Coches:"));

        Agrupados.add(bAnyadirCircuito);
        bAnyadirCircuito.setText("Crear coche");

        Agrupados.add(bModificarCircuito);
        bModificarCircuito.setText("Dar de baja coche");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAnyadirCircuito)
                    .addComponent(bModificarCircuito))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAnyadirCircuito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bModificarCircuito))
        );

        Resultados.setColumns(20);
        Resultados.setRows(5);
        jScrollPane1.setViewportView(Resultados);

        Accion.setText("Realizar Accion");
        Accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrenamiento:"));

        Agrupados.add(bAnyadirCircuito1);
        bAnyadirCircuito1.setText("Entrenar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(bAnyadirCircuito1)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(bAnyadirCircuito1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(205, 205, 205)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(Accion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Accion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionActionPerformed

    //Añade Escuderia
        if(bAnyadirEscuderia.isSelected()){
            jpAñadeEscuderia pAñade = new jpAñadeEscuderia();
            if(JOptionPane.showConfirmDialog(this, pAñade, "Añade Escuderia",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
            == JOptionPane.OK_OPTION) {
                    Escuderia escuderia = new Escuderia(pAñade.getNombre(), pAñade.getPais(),
                    pAñade.getAnyoFundacion(), pAñade.getPresupuesto(), pAñade.getDirectivos());
                Formula1UI.formula1.añadirEscuderia(escuderia);
                Resultados.setText ("La escuderia se ha insertado satisfactoriamente");
            }
        }
    //Modificar Escuderia
        else if(bModificarEscuderia.isSelected()){
          if(!Formula1UI.formula1.escuderias.isEmpty()){
            jpEditaEscuderia pEdita = new jpEditaEscuderia();
            if(JOptionPane.showConfirmDialog(this, pEdita, "Modificar Escuderia",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
            == JOptionPane.OK_OPTION) {
                try {
                    Formula1UI.formula1.modificarEscuderia(pEdita.getNumero()-1, pEdita.getNombre(), pEdita.getPais(),
                            pEdita.getAnyoFundacion(), pEdita.getPresupuesto());
                } catch (ParseException ex) {
                    Logger.getLogger(jpEscuderia.class.getName()).log(Level.SEVERE, null, ex);
                }
                Resultados.setText ("La escuderia se ha modificado satisfactoriamente");
            }
          }
        }
    //Borrar Escuderia
        else if(bBorrarEscuderia.isSelected()){
          if(!Formula1UI.formula1.escuderias.isEmpty()){
            jpBorraEscuderia pBorra = new jpBorraEscuderia();
            if(JOptionPane.showConfirmDialog(this, pBorra, "Borrar Escuderia",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
                == JOptionPane.OK_OPTION) {
                    Escuderia escuderia=Formula1UI.formula1.escuderias.get(pBorra.getNumero()-1);
                    Formula1UI.formula1.borrarEscuderia(escuderia);
                    Resultados.setText ("La escuderia se ha borrado satisfactoriamente");
                }
            }else{
              Resultados.setText ("No hay escuderias");
            }
        }
    //Consultar Escuderia
        else if(bConsultarEscuderia.isSelected()){
          if(!Formula1UI.formula1.escuderias.isEmpty()){
            jpConsultaEscuderia pConsulta = new jpConsultaEscuderia();
            if(JOptionPane.showConfirmDialog(this, pConsulta, "Consultar Escuderia",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
                == JOptionPane.OK_OPTION) {
                    Escuderia escuderia=Formula1UI.formula1.escuderias.get(pConsulta.getNumero()-1);
                    Escuderia x= Formula1UI.formula1.consultarEscuderia(escuderia);
                    Resultados.setText (x.toString());
                }
            }else{
                Resultados.setText ("No hay escuderias");
            }
        }
}//GEN-LAST:event_AccionActionPerformed

    private void bConsultarEscuderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarEscuderiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bConsultarEscuderiaActionPerformed

    private void bConsultarEscuderia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarEscuderia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bConsultarEscuderia1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jpEscuderia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accion;
    private javax.swing.ButtonGroup Agrupados;
    private javax.swing.JTextArea Resultados;
    private javax.swing.JRadioButton bAnyadirCircuito;
    private javax.swing.JRadioButton bAnyadirCircuito1;
    private javax.swing.JRadioButton bAnyadirPiloto;
    private javax.swing.JRadioButton bBorrarPiloto;
    private javax.swing.JRadioButton bConsultarEscuderia;
    private javax.swing.JRadioButton bConsultarEscuderia1;
    private javax.swing.JRadioButton bConsultarPiloto;
    private javax.swing.JRadioButton bModificarCircuito;
    private javax.swing.JRadioButton bModificarPiloto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
