
/*
 * jpIañade.java
 *
 * Created on 07-dic-2010, 16:09:42
 */

package Formula1;
import java.util.*;
import java.text.*;

/**
 *
 * @author July
 */
public class jpIañade extends javax.swing.JPanel implements Enum{

    /** Creates new form jpIañade */
    public jpIañade() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNombre = new javax.swing.JLabel();
        jHoras = new javax.swing.JLabel();
        jLugar = new javax.swing.JLabel();
        jInicio = new javax.swing.JLabel();
        bNombre = new javax.swing.JTextField();
        bHoras = new javax.swing.JTextField();
        bLugar = new javax.swing.JTextField();
        bInicio = new javax.swing.JTextField();
        Indicacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDoctorado = new javax.swing.JRadioButton();
        jMaster = new javax.swing.JRadioButton();
        jGrado = new javax.swing.JRadioButton();
        jFP = new javax.swing.JRadioButton();
        jBachillerato = new javax.swing.JRadioButton();
        jSecundaria = new javax.swing.JRadioButton();
        jSinEstudios = new javax.swing.JRadioButton();

        jNombre.setText("Nombre:");

        jHoras.setText("Horas:");

        jLugar.setText("Lugar:");

        jInicio.setText("Fecha de inicio:");

        Indicacion.setText("INTRODUCE LOS DATOS DEL CURSO:");

        jLabel1.setText("DD/MM/YYYY");

        jLabel4.setText("Estudios Minimos requeridos:");

        jDoctorado.setText("Doctorado");

        jMaster.setText("Master");

        jGrado.setText("Grado");

        jFP.setText("FP");

        jBachillerato.setText("Bachillerato");

        jSecundaria.setText("Secundaria");

        jSinEstudios.setText("Sin estudios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Indicacion)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jHoras)
                                    .addComponent(jNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLugar)
                                    .addComponent(jInicio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(bInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDoctorado)
                                    .addComponent(jMaster)
                                    .addComponent(jGrado)
                                    .addComponent(jFP)
                                    .addComponent(jBachillerato)
                                    .addComponent(jSecundaria)
                                    .addComponent(jSinEstudios))
                                .addGap(31, 31, 31)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Indicacion)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNombre)
                            .addComponent(bNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jHoras)
                            .addComponent(bHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLugar)
                                .addGap(45, 45, 45)
                                .addComponent(jInicio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addGap(35, 35, 35)
                        .addComponent(jDoctorado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jMaster)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jGrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBachillerato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSecundaria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSinEstudios)))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents
public String getNombre () {
    return bNombre.getText();
}

public int getHoras () {
    int s=0;
    if(!bHoras.getText().equals("")){
        return Integer.parseInt(bHoras.getText());
    }else{
        return s;
    }
}

public E2 getTitulacion () {

        E2 s= E2.SIN_ESTUDIOS;
        if (jDoctorado.isSelected()) {s = E2.DOCTORADO;}
        else if (jMaster.isSelected()) { s= E2.MASTER;}
        else if (jGrado.isSelected()) { s= E2.GRADO;}
        else if (jFP.isSelected()) { s= E2.FP;}
        else if (jBachillerato.isSelected()) { s = E2.BACHILLERATO;}
        else if (jSecundaria.isSelected()) { s= E2.SECUNDARIA;}
   
        return s;
}

public String getLugar () {
    return bLugar.getText();
}

public Date getInicio () throws ParseException {
    SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yyyy");
    Date f= formatoDelTexto.parse(bInicio.getText());
    return f;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Indicacion;
    private javax.swing.JTextField bHoras;
    private javax.swing.JTextField bInicio;
    private javax.swing.JTextField bLugar;
    private javax.swing.JTextField bNombre;
    private javax.swing.JRadioButton jBachillerato;
    private javax.swing.JRadioButton jDoctorado;
    private javax.swing.JRadioButton jFP;
    private javax.swing.JRadioButton jGrado;
    private javax.swing.JLabel jHoras;
    private javax.swing.JLabel jInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLugar;
    private javax.swing.JRadioButton jMaster;
    private javax.swing.JLabel jNombre;
    private javax.swing.JRadioButton jSecundaria;
    private javax.swing.JRadioButton jSinEstudios;
    // End of variables declaration//GEN-END:variables

}
