/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pBorrarse.java
 *
 * Created on 06-dic-2010, 19:14:59
 */

package Formula1;

/**
 *
 * @author AlbertoMartin
 */
public class pBorrarse extends javax.swing.JPanel {

    /** Creates new form pBorrarse */
    public pBorrarse() {
        initComponents();
        jTextArea1.setText(Formula1UI.inem.mostrarCursos()
                +"El numero total de cursos es: " + Formula1UI.inem.cursos.size());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lDNI = new javax.swing.JLabel();
        lIDE = new javax.swing.JLabel();
        tDNI = new javax.swing.JTextField();
        tIDE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Borrarse de Curso"));

        lDNI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lDNI.setText("DNI del Usuario:");

        lIDE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lIDE.setText("Identificador del Curso:");

        tDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDNIActionPerformed(evt);
            }
        });

        tIDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIDEActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Escoga un curso de entre los disponibles:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lIDE)
                            .addComponent(lDNI))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tDNI)
                            .addComponent(tIDE, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDNI)
                    .addComponent(tDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lIDE)
                    .addComponent(tIDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDNIActionPerformed

    private void tIDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIDEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIDEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lDNI;
    private javax.swing.JLabel lIDE;
    private javax.swing.JTextField tDNI;
    private javax.swing.JTextField tIDE;
    // End of variables declaration//GEN-END:variables
    public long getDNI() {
        return Long.parseLong(tIDE.getText());
    }

    public int getIdentificador() {
        return Integer.parseInt(tIDE.getText());
    }
}
