/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pConsultar.java
 *
 * Created on 06-dic-2010, 19:09:23
 */

package Formula1;

/**
 *
 * @author AlbertoMartin
 */
public class pConsultar extends javax.swing.JPanel {

    /** Creates new form pConsultar */
    public pConsultar() {
        initComponents();
        jTextArea1.setText(Formula1UI.inem.mostrarCursos()
                +"El numero total de cursos es: " + Formula1UI.inem.cursos.size());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lDNI = new javax.swing.JLabel();
        tDNI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Curso"));

        lDNI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lDNI.setText("DNI del usuario:");

        tDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDNIActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lDNI)
                        .addGap(61, 61, 61)
                        .addComponent(tDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDNI)
                    .addComponent(tDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDNIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lDNI;
    private javax.swing.JTextField tDNI;
    // End of variables declaration//GEN-END:variables
    public long getDNI() {
        return Long.parseLong(tDNI.getText());
    }
}
