/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pVidaLaboral.java
 *
 * Created on 06-dic-2010, 19:19:01
 */

package Formula1;

/**
 *
 * @author AlbertoMartin
 */
public class pVidaLaboral extends javax.swing.JPanel {

    /** Creates new form pVidaLaboral */
    public pVidaLaboral() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lDNI = new javax.swing.JLabel();
        tDNI = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Vida Laboral"));

        lDNI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lDNI.setText("DNI del Usuario:");

        tDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDNIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lDNI)
                .addGap(18, 18, 18)
                .addComponent(tDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDNI)
                    .addComponent(tDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDNIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lDNI;
    private javax.swing.JTextField tDNI;
    // End of variables declaration//GEN-END:variables

   public long getDNI() {
        return Long.parseLong(tDNI.getText());
    }
}
